### ISSUE TITLE
Persistant solution throughout upgrades?

### ISSUE THREAD

**Issue by a-torgovitsky** [kirked/dropbox-status-icons#1]
Thanks for this great fix!

I find that when Dropbox (automatically) updates itself, the icon directory gets overwritten and I have to apply the fix again.
Do you know of a workaround for this?

**Comment by kirked** [comment]
No, unfortunately I don't have an automatic fix. I think I set up a script that I could manually run to reapply the icons after.

**Comment by a-torgovitsky** [comment]
I suppose that's easy enough to do. Thanks again!
